version: '3.8'
services:
  db:
    container_name: question_db
    image: postgres:13.0-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: questions_db
    expose:
      - "5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
  web:
    container_name: question_backend
    build: .
    expose:
      - "8000"
    depends_on:
      - db
    volumes:
      - ./media:/app/media
  nginx:
    container_name: question_nginx
    build: ./nginx
    depends_on:
      - web
    ports:
      - 2233:80
    volumes:
      - ./media:/opt/media

volumes:
  postgres_data: