# Generated by Django 4.2.6 on 2023-10-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_filter_telgramuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='telgramuser',
            name='name',
            field=models.CharField(default='Аноним (default value)', max_length=200),
        ),
        migrations.AddField(
            model_name='telgramuser',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
