# Generated by Django 4.2.6 on 2023-10-28 06:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_telgramuser_name_telgramuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telgramuser',
            name='selected_filter',
            field=models.ForeignKey(default=core.models.get_default_filter, on_delete=models.SET(core.models.get_default_filter), to='core.filter'),
        ),
    ]
