# Generated by Django 4.2.6 on 2023-10-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_telgramuser_selected_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telgramuser',
            name='telegram_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
