# Generated by Django 4.2.6 on 2023-10-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_telgramuser_telegram_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelgramUser',
            new_name='TelegramUser',
        ),
    ]
